-- ============================================================================
-- OPTION A: CREATE MISSING FAMILIES RECORDS
-- ============================================================================
-- This creates families table entries for orphaned family_ids
-- Run this if the orphaned profiles SHOULD have valid families
-- NOTE: Works with both TEXT and UUID types (uses casting for safety)
-- ============================================================================

DO $$
DECLARE
  v_family_id_text TEXT;
    v_created_count INTEGER := 0;
      v_parent_id UUID;
      BEGIN
        RAISE NOTICE '====================================';
          RAISE NOTICE 'Creating missing families records...';
            RAISE NOTICE '====================================';
              
                -- For each distinct orphaned family_id (cast to text for type safety)
                  FOR v_family_id_text IN (
                      SELECT DISTINCT p.family_id::text
                          FROM profiles p
                              WHERE p.family_id IS NOT NULL
                                    AND NOT EXISTS (
                                            SELECT 1 FROM families f 
                                                    WHERE f.id::text = p.family_id::text
                                                          )
                                                            ) LOOP
                                                                
                                                                    -- Try to find a parent in this family
                                                                        SELECT id INTO v_parent_id
                                                                            FROM profiles
                                                                                WHERE family_id::text = v_family_id_text 
                                                                                      AND role = 'parent'
                                                                                          LIMIT 1;
                                                                                              
                                                                                                  -- Create the family record (adapt based on your actual families table schema)
                                                                                                      -- Check what columns exist first
                                                                                                          IF EXISTS (
                                                                                                                SELECT 1 FROM information_schema.columns 
                                                                                                                      WHERE table_schema = 'public' 
                                                                                                                              AND table_name = 'families' 
                                                                                                                                      AND column_name = 'created_by'
                                                                                                                                          ) THEN
                                                                                                                                                -- Has created_by column
                                                                                                                                                      INSERT INTO families (id, created_at, created_by)
                                                                                                                                                            VALUES (v_family_id_text, NOW(), v_parent_id)
                                                                                                                                                                  ON CONFLICT (id) DO NOTHING;
                                                                                                                                                                      ELSE
                                                                                                                                                                            -- No created_by column
                                                                                                                                                                                  IF EXISTS (
                                                                                                                                                                                          SELECT 1 FROM information_schema.columns 
                                                                                                                                                                                                  WHERE table_schema = 'public' 
                                                                                                                                                                                                            AND table_name = 'families' 
                                                                                                                                                                                                                      AND column_name = 'created_at'
                                                                                                                                                                                                                            ) THEN
                                                                                                                                                                                                                                    INSERT INTO families (id, created_at)
                                                                                                                                                                                                                                            VALUES (v_family_id_text, NOW())
                                                                                                                                                                                                                                                    ON CONFLICT (id) DO NOTHING;
                                                                                                                                                                                                                                                          ELSE
                                                                                                                                                                                                                                                                  -- Minimal schema - just id
                                                                                                                                                                                                                                                                          INSERT INTO families (id)
                                                                                                                                                                                                                                                                                  VALUES (v_family_id_text)
                                                                                                                                                                                                                                                                                          ON CONFLICT (id) DO NOTHING;
                                                                                                                                                                                                                                                                                                END IF;
                                                                                                                                                                                                                                                                                                    END IF;
                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                            v_created_count := v_created_count + 1;
                                                                                                                                                                                                                                                                                                                RAISE NOTICE '✅ Created family record for family_id: %', v_family_id_text;
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                      END LOOP;
                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                          RAISE NOTICE '====================================';
                                                                                                                                                                                                                                                                                                                            RAISE NOTICE '✅ Created % family records', v_created_count;
                                                                                                                                                                                                                                                                                                                              RAISE NOTICE '====================================';
                                                                                                                                                                                                                                                                                                                              END $$;

                                                                                                                                                                                                                                                                                                                              -- Verify the fix
                                                                                                                                                                                                                                                                                                                              SELECT 
                                                                                                                                                                                                                                                                                                                                'Verification: Orphaned profiles after fix' as check_name,
                                                                                                                                                                                                                                                                                                                                  COUNT(*) as remaining_orphans
                                                                                                                                                                                                                                                                                                                                  FROM profiles p
                                                                                                                                                                                                                                                                                                                                  WHERE p.family_id IS NOT NULL
                                                                                                                                                                                                                                                                                                                                    AND NOT EXISTS (
                                                                                                                                                                                                                                                                                                                                        SELECT 1 FROM families f 
                                                                                                                                                                                                                                                                                                                                            WHERE f.id::text = p.family_id::text
                                                                                                                                                                                                                                                                                                                                              );

                                                                                                                                                                                                                                                                                                                                              -- Show created families
                                                                                                                                                                                                                                                                                                                                              SELECT 
                                                                                                                                                                                                                                                                                                                                                'Newly Created Families' as check_name,
                                                                                                                                                                                                                                                                                                                                                  f.id::text as family_id,
                                                                                                                                                                                                                                                                                                                                                    f.created_at,
                                                                                                                                                                                                                                                                                                                                                      COUNT(p.id) as member_count,
                                                                                                                                                                                                                                                                                                                                                        STRING_AGG(p.email, ', ' ORDER BY p.email) as members
                                                                                                                                                                                                                                                                                                                                                        FROM families f
                                                                                                                                                                                                                                                                                                                                                        JOIN profiles p ON p.family_id::text = f.id::text
                                                                                                                                                                                                                                                                                                                                                        WHERE f.created_at > NOW() - INTERVAL '5 minutes'
                                                                                                                                                                                                                                                                                                                                                        GROUP BY f.id, f.created_at
                                                                                                                                                                                                                                                                                                                                                        ORDER BY f.created_at DESC;
                                                                                                                                                                                                                                                                                                                                                        