-- ============================================================================
-- WORKING GAMIFICATION FIX - Simplified with JSONB (No Ambiguity)
-- ============================================================================
-- This version uses JSONB returns throughout to eliminate column ambiguity
-- Run this in Supabase SQL Editor
-- ============================================================================

-- ============================================================================
-- 1. FIX add_user_xp - SECURITY DEFINER
-- ============================================================================
CREATE OR REPLACE FUNCTION add_user_xp(p_user_id UUID, p_xp_amount INTEGER)
RETURNS VOID
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_current_level INTEGER;
    v_total_xp INTEGER;
      v_xp_needed INTEGER;
        v_new_level INTEGER;
        BEGIN
          SELECT current_level, total_xp, xp_for_next_level
            INTO v_current_level, v_total_xp, v_xp_needed
              FROM user_levels
                WHERE user_id = p_user_id;

                  IF NOT FOUND THEN
                      INSERT INTO user_levels (user_id, current_level, total_xp, xp_for_next_level, level_title)
                          VALUES (p_user_id, 1, p_xp_amount, calculate_xp_for_level(1), get_level_title(1));
                              RETURN;
                                END IF;

                                  v_total_xp := v_total_xp + p_xp_amount;
                                    v_new_level := v_current_level;

                                      WHILE v_total_xp >= v_xp_needed AND v_new_level < 100 LOOP
                                          v_new_level := v_new_level + 1;
                                              v_xp_needed := calculate_xp_for_level(v_new_level);
                                                END LOOP;

                                                  UPDATE user_levels
                                                    SET current_level = v_new_level,
                                                          total_xp = v_total_xp,
                                                                xp_for_next_level = v_xp_needed,
                                                                      level_title = get_level_title(v_new_level),
                                                                            updated_at = NOW()
                                                                              WHERE user_id = p_user_id;
                                                                              END;
                                                                              $$ LANGUAGE plpgsql;

                                                                              -- ============================================================================
                                                                              -- 2. FIX award_task_xp - SECURITY DEFINER
                                                                              -- ============================================================================
                                                                              CREATE OR REPLACE FUNCTION award_task_xp(
                                                                                p_user_id UUID,
                                                                                  p_task_points INTEGER
                                                                                  )
                                                                                  RETURNS JSONB 
                                                                                  SECURITY DEFINER
                                                                                  SET search_path = public
                                                                                  AS $$
                                                                                  DECLARE
                                                                                    v_xp_to_award INTEGER;
                                                                                      v_level_data RECORD;
                                                                                      BEGIN
                                                                                        v_xp_to_award := p_task_points * 10;
                                                                                          PERFORM add_user_xp(p_user_id, v_xp_to_award);
                                                                                            
                                                                                              SELECT current_level, total_xp, xp_for_next_level
                                                                                                INTO v_level_data
                                                                                                  FROM user_levels
                                                                                                    WHERE user_id = p_user_id;
                                                                                                      
                                                                                                        RETURN jsonb_build_object(
                                                                                                            'xp_awarded', v_xp_to_award,
                                                                                                                'current_level', COALESCE(v_level_data.current_level, 1),
                                                                                                                    'total_xp', COALESCE(v_level_data.total_xp, 0),
                                                                                                                        'xp_for_next_level', COALESCE(v_level_data.xp_for_next_level, 100)
                                                                                                                          );
                                                                                                                          END;
                                                                                                                          $$ LANGUAGE plpgsql;

                                                                                                                          -- ============================================================================
                                                                                                                          -- 3. FIX update_task_streak - SECURITY DEFINER
                                                                                                                          -- ============================================================================
                                                                                                                          CREATE OR REPLACE FUNCTION update_task_streak(p_user_id UUID)
                                                                                                                          RETURNS JSONB
                                                                                                                          SECURITY DEFINER
                                                                                                                          SET search_path = public
                                                                                                                          AS $$
                                                                                                                          DECLARE
                                                                                                                            v_last_completed DATE;
                                                                                                                              v_today DATE;
                                                                                                                                v_current_streak INTEGER;
                                                                                                                                  v_longest_streak INTEGER;
                                                                                                                                    v_streak_record RECORD;
                                                                                                                                    BEGIN
                                                                                                                                      v_today := CURRENT_DATE;
                                                                                                                                        
                                                                                                                                          SELECT DATE(MAX(completed_at)) INTO v_last_completed
                                                                                                                                            FROM tasks
                                                                                                                                              WHERE assigned_to = p_user_id AND completed = true AND approved = true;
                                                                                                                                                
                                                                                                                                                  SELECT * INTO v_streak_record
                                                                                                                                                    FROM user_streaks
                                                                                                                                                      WHERE user_id = p_user_id;
                                                                                                                                                        
                                                                                                                                                          IF v_streak_record IS NULL THEN
                                                                                                                                                              INSERT INTO user_streaks (user_id, current_streak, longest_streak, last_completion_date)
                                                                                                                                                                  VALUES (p_user_id, 1, 1, v_today)
                                                                                                                                                                      RETURNING * INTO v_streak_record;
                                                                                                                                                                        ELSE
                                                                                                                                                                            v_current_streak := v_streak_record.current_streak;
                                                                                                                                                                                v_longest_streak := v_streak_record.longest_streak;
                                                                                                                                                                                    
                                                                                                                                                                                        IF v_streak_record.last_completion_date = v_today THEN
                                                                                                                                                                                              NULL;
                                                                                                                                                                                                  ELSIF v_streak_record.last_completion_date = v_today - INTERVAL '1 day' THEN
                                                                                                                                                                                                        v_current_streak := v_current_streak + 1;
                                                                                                                                                                                                              v_longest_streak := GREATEST(v_longest_streak, v_current_streak);
                                                                                                                                                                                                                    
                                                                                                                                                                                                                          UPDATE user_streaks
                                                                                                                                                                                                                                SET current_streak = v_current_streak,
                                                                                                                                                                                                                                          longest_streak = v_longest_streak,
                                                                                                                                                                                                                                                    last_completion_date = v_today
                                                                                                                                                                                                                                                          WHERE user_id = p_user_id;
                                                                                                                                                                                                                                                              ELSE
                                                                                                                                                                                                                                                                    v_current_streak := 1;
                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                UPDATE user_streaks
                                                                                                                                                                                                                                                                                      SET current_streak = 1,
                                                                                                                                                                                                                                                                                                last_completion_date = v_today
                                                                                                                                                                                                                                                                                                      WHERE user_id = p_user_id;
                                                                                                                                                                                                                                                                                                          END IF;
                                                                                                                                                                                                                                                                                                            END IF;
                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                RETURN jsonb_build_object(
                                                                                                                                                                                                                                                                                                                    'current_streak', COALESCE(v_current_streak, 1),
                                                                                                                                                                                                                                                                                                                        'longest_streak', COALESCE(v_longest_streak, 1),
                                                                                                                                                                                                                                                                                                                            'last_completed', v_today
                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                              END;
                                                                                                                                                                                                                                                                                                                              $$ LANGUAGE plpgsql;

                                                                                                                                                                                                                                                                                                                              -- ============================================================================
                                                                                                                                                                                                                                                                                                                              -- 4. SIMPLIFIED check_and_unlock_achievements - Returns JSONB Array
                                                                                                                                                                                                                                                                                                                              -- ============================================================================
                                                                                                                                                                                                                                                                                                                              DROP FUNCTION IF EXISTS check_and_unlock_achievements(UUID);

                                                                                                                                                                                                                                                                                                                              CREATE FUNCTION check_and_unlock_achievements(p_user_id UUID)
                                                                                                                                                                                                                                                                                                                              RETURNS JSONB
                                                                                                                                                                                                                                                                                                                              SECURITY DEFINER
                                                                                                                                                                                                                                                                                                                              SET search_path = public
                                                                                                                                                                                                                                                                                                                              AS $$
                                                                                                                                                                                                                                                                                                                              DECLARE
                                                                                                                                                                                                                                                                                                                                v_completed_tasks INTEGER;
                                                                                                                                                                                                                                                                                                                                  v_total_points INTEGER;
                                                                                                                                                                                                                                                                                                                                    v_current_streak INTEGER;
                                                                                                                                                                                                                                                                                                                                      v_achievements JSONB := '[]'::JSONB;
                                                                                                                                                                                                                                                                                                                                        v_ach RECORD;
                                                                                                                                                                                                                                                                                                                                        BEGIN
                                                                                                                                                                                                                                                                                                                                          -- Get user stats
                                                                                                                                                                                                                                                                                                                                            SELECT 
                                                                                                                                                                                                                                                                                                                                                COUNT(CASE WHEN completed = true AND approved = true THEN 1 END),
                                                                                                                                                                                                                                                                                                                                                    COALESCE(SUM(CASE WHEN completed = true AND approved = true THEN points ELSE 0 END), 0)
                                                                                                                                                                                                                                                                                                                                                      INTO v_completed_tasks, v_total_points
                                                                                                                                                                                                                                                                                                                                                        FROM tasks
                                                                                                                                                                                                                                                                                                                                                          WHERE assigned_to = p_user_id;
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                              -- Get current streak
                                                                                                                                                                                                                                                                                                                                                                SELECT COALESCE(current_streak, 0) INTO v_current_streak
                                                                                                                                                                                                                                                                                                                                                                  FROM user_streaks
                                                                                                                                                                                                                                                                                                                                                                    WHERE user_id = p_user_id;
                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                        -- Check each achievement
                                                                                                                                                                                                                                                                                                                                                                          FOR v_ach IN 
                                                                                                                                                                                                                                                                                                                                                                              SELECT a.id, a.title, a.requirement_type, a.requirement_value
                                                                                                                                                                                                                                                                                                                                                                                  FROM achievements a
                                                                                                                                                                                                                                                                                                                                                                                      WHERE NOT EXISTS (
                                                                                                                                                                                                                                                                                                                                                                                            SELECT 1 FROM user_achievements ua
                                                                                                                                                                                                                                                                                                                                                                                                  WHERE ua.user_id = p_user_id AND ua.achievement_id = a.id AND ua.is_earned = true
                                                                                                                                                                                                                                                                                                                                                                                                      )
                                                                                                                                                                                                                                                                                                                                                                                                        LOOP
                                                                                                                                                                                                                                                                                                                                                                                                            -- Check criteria
                                                                                                                                                                                                                                                                                                                                                                                                                IF (v_ach.requirement_type = 'task_count' AND v_completed_tasks >= v_ach.requirement_value) OR
                                                                                                                                                                                                                                                                                                                                                                                                                       (v_ach.requirement_type = 'points_earned' AND v_total_points >= v_ach.requirement_value) OR
                                                                                                                                                                                                                                                                                                                                                                                                                              (v_ach.requirement_type = 'streak_days' AND v_current_streak >= v_ach.requirement_value) THEN
                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                          -- Unlock achievement
                                                                                                                                                                                                                                                                                                                                                                                                                                                INSERT INTO user_achievements (user_id, achievement_id, is_earned, progress)
                                                                                                                                                                                                                                                                                                                                                                                                                                                      VALUES (p_user_id, v_ach.id, true, v_ach.requirement_value)
                                                                                                                                                                                                                                                                                                                                                                                                                                                            ON CONFLICT (user_id, achievement_id) 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  DO UPDATE SET is_earned = true, earned_at = NOW();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              -- Add to results array
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    v_achievements := v_achievements || jsonb_build_object(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'achievement_id', v_ach.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'achievement_title', v_ach.title
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              END IF;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                END LOOP;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    RETURN v_achievements;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    END;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $$ LANGUAGE plpgsql;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    -- ============================================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    -- 5. SIMPLIFIED process_task_approval_gamification
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    -- ============================================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE OR REPLACE FUNCTION process_task_approval_gamification(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      p_user_id UUID,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        p_task_points INTEGER
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        RETURNS JSONB
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        SECURITY DEFINER
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        SET search_path = public
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        AS $$
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        DECLARE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          v_xp_result JSONB;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            v_streak_result JSONB;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              v_achievements_result JSONB;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              BEGIN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                -- Award XP
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  v_xp_result := award_task_xp(p_user_id, p_task_points);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      -- Update streak
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        v_streak_result := update_task_streak(p_user_id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -- Check and unlock achievements (now returns JSONB array directly)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              v_achievements_result := check_and_unlock_achievements(p_user_id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  -- Return combined results
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    RETURN jsonb_build_object(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'xp', v_xp_result,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'streak', v_streak_result,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'unlocked_achievements', v_achievements_result
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  END;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  $$ LANGUAGE plpgsql;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  -- ============================================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  -- 6. TRIGGER FUNCTION - SECURITY DEFINER
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  -- ============================================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  CREATE OR REPLACE FUNCTION task_approval_with_gamification()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  RETURNS TRIGGER
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  SECURITY DEFINER
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  SET search_path = public
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  AS $$
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  DECLARE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    v_gamification_result JSONB;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    BEGIN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      IF NEW.approved = true AND (OLD.approved IS NULL OR OLD.approved = false) THEN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          v_gamification_result := process_task_approval_gamification(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                NEW.assigned_to,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      NEW.points
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  RAISE NOTICE 'Gamification processed: %', v_gamification_result;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    END IF;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        RETURN NEW;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        END;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $$ LANGUAGE plpgsql;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        -- ============================================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        -- VERIFICATION
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        -- ============================================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        SELECT 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          p.proname as "Function",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            CASE p.prosecdef 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                WHEN true THEN '✅ SECURITY DEFINER' 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ELSE '❌ SECURITY INVOKER' 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      END as "Security Mode"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      FROM pg_proc p
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      JOIN pg_namespace n ON n.oid = p.pronamespace
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      WHERE n.nspname = 'public'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        AND p.proname IN (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'add_user_xp',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'award_task_xp',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'update_task_streak',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'check_and_unlock_achievements',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'process_task_approval_gamification',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'task_approval_with_gamification'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ORDER BY p.proname;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  -- ============================================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  -- ✅ This version eliminates ALL ambiguity by:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  -- 1. Using JSONB returns everywhere (no TABLE return types)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  -- 2. No OUT parameters (no ambiguous column references)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  -- 3. All functions are SECURITY DEFINER
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  -- 4. Simple, clean implementation
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  -- ============================================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  